/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.dr.dataRetrieval;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Add Prefix</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.dr.dataRetrieval.DataRetrievalPackage#getAddPrefix()
 * @model
 * @generated
 */
public interface AddPrefix extends Rename, RenameAll
{
} // AddPrefix
