/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.dr.dataRetrieval;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Add Suffix</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.dr.dataRetrieval.DataRetrievalPackage#getAddSuffix()
 * @model
 * @generated
 */
public interface AddSuffix extends Rename, RenameAll
{
} // AddSuffix
