/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.dr.dataRetrieval;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Config List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.dr.dataRetrieval.ConfigList#getSource <em>Source</em>}</li>
 *   <li>{@link org.xtext.example.dr.dataRetrieval.ConfigList#getPath <em>Path</em>}</li>
 *   <li>{@link org.xtext.example.dr.dataRetrieval.ConfigList#getKeysToExtract <em>Keys To Extract</em>}</li>
 *   <li>{@link org.xtext.example.dr.dataRetrieval.ConfigList#getRenameAll <em>Rename All</em>}</li>
 *   <li>{@link org.xtext.example.dr.dataRetrieval.ConfigList#getFilter <em>Filter</em>}</li>
 *   <li>{@link org.xtext.example.dr.dataRetrieval.ConfigList#getThreshold <em>Threshold</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.dr.dataRetrieval.DataRetrievalPackage#getConfigList()
 * @model
 * @generated
 */
public interface ConfigList extends EObject
{
  /**
   * Returns the value of the '<em><b>Source</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source</em>' containment reference.
   * @see #setSource(Source)
   * @see org.xtext.example.dr.dataRetrieval.DataRetrievalPackage#getConfigList_Source()
   * @model containment="true"
   * @generated
   */
  Source getSource();

  /**
   * Sets the value of the '{@link org.xtext.example.dr.dataRetrieval.ConfigList#getSource <em>Source</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source</em>' containment reference.
   * @see #getSource()
   * @generated
   */
  void setSource(Source value);

  /**
   * Returns the value of the '<em><b>Path</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Path</em>' containment reference.
   * @see #setPath(Path)
   * @see org.xtext.example.dr.dataRetrieval.DataRetrievalPackage#getConfigList_Path()
   * @model containment="true"
   * @generated
   */
  Path getPath();

  /**
   * Sets the value of the '{@link org.xtext.example.dr.dataRetrieval.ConfigList#getPath <em>Path</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Path</em>' containment reference.
   * @see #getPath()
   * @generated
   */
  void setPath(Path value);

  /**
   * Returns the value of the '<em><b>Keys To Extract</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Keys To Extract</em>' containment reference.
   * @see #setKeysToExtract(KeysToExtract)
   * @see org.xtext.example.dr.dataRetrieval.DataRetrievalPackage#getConfigList_KeysToExtract()
   * @model containment="true"
   * @generated
   */
  KeysToExtract getKeysToExtract();

  /**
   * Sets the value of the '{@link org.xtext.example.dr.dataRetrieval.ConfigList#getKeysToExtract <em>Keys To Extract</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Keys To Extract</em>' containment reference.
   * @see #getKeysToExtract()
   * @generated
   */
  void setKeysToExtract(KeysToExtract value);

  /**
   * Returns the value of the '<em><b>Rename All</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rename All</em>' containment reference.
   * @see #setRenameAll(RenameAll)
   * @see org.xtext.example.dr.dataRetrieval.DataRetrievalPackage#getConfigList_RenameAll()
   * @model containment="true"
   * @generated
   */
  RenameAll getRenameAll();

  /**
   * Sets the value of the '{@link org.xtext.example.dr.dataRetrieval.ConfigList#getRenameAll <em>Rename All</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rename All</em>' containment reference.
   * @see #getRenameAll()
   * @generated
   */
  void setRenameAll(RenameAll value);

  /**
   * Returns the value of the '<em><b>Filter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Filter</em>' containment reference.
   * @see #setFilter(Filter)
   * @see org.xtext.example.dr.dataRetrieval.DataRetrievalPackage#getConfigList_Filter()
   * @model containment="true"
   * @generated
   */
  Filter getFilter();

  /**
   * Sets the value of the '{@link org.xtext.example.dr.dataRetrieval.ConfigList#getFilter <em>Filter</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Filter</em>' containment reference.
   * @see #getFilter()
   * @generated
   */
  void setFilter(Filter value);

  /**
   * Returns the value of the '<em><b>Threshold</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Threshold</em>' containment reference.
   * @see #setThreshold(Threshold)
   * @see org.xtext.example.dr.dataRetrieval.DataRetrievalPackage#getConfigList_Threshold()
   * @model containment="true"
   * @generated
   */
  Threshold getThreshold();

  /**
   * Sets the value of the '{@link org.xtext.example.dr.dataRetrieval.ConfigList#getThreshold <em>Threshold</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Threshold</em>' containment reference.
   * @see #getThreshold()
   * @generated
   */
  void setThreshold(Threshold value);

} // ConfigList
