/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.dr.dataRetrieval;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.example.dr.dataRetrieval.DataRetrievalPackage
 * @generated
 */
public interface DataRetrievalFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DataRetrievalFactory eINSTANCE = org.xtext.example.dr.dataRetrieval.impl.DataRetrievalFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Retrieve</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Retrieve</em>'.
   * @generated
   */
  Retrieve createRetrieve();

  /**
   * Returns a new object of class '<em>Dest</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dest</em>'.
   * @generated
   */
  Dest createDest();

  /**
   * Returns a new object of class '<em>Source Folder</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Source Folder</em>'.
   * @generated
   */
  SourceFolder createSourceFolder();

  /**
   * Returns a new object of class '<em>Config List</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Config List</em>'.
   * @generated
   */
  ConfigList createConfigList();

  /**
   * Returns a new object of class '<em>Op List</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Op List</em>'.
   * @generated
   */
  OpList createOpList();

  /**
   * Returns a new object of class '<em>Source</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Source</em>'.
   * @generated
   */
  Source createSource();

  /**
   * Returns a new object of class '<em>Path</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Path</em>'.
   * @generated
   */
  Path createPath();

  /**
   * Returns a new object of class '<em>Keys To Extract</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Keys To Extract</em>'.
   * @generated
   */
  KeysToExtract createKeysToExtract();

  /**
   * Returns a new object of class '<em>Key</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Key</em>'.
   * @generated
   */
  Key createKey();

  /**
   * Returns a new object of class '<em>Rename</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rename</em>'.
   * @generated
   */
  Rename createRename();

  /**
   * Returns a new object of class '<em>Rename All</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rename All</em>'.
   * @generated
   */
  RenameAll createRenameAll();

  /**
   * Returns a new object of class '<em>Full Rename</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Full Rename</em>'.
   * @generated
   */
  FullRename createFullRename();

  /**
   * Returns a new object of class '<em>Add Prefix</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Add Prefix</em>'.
   * @generated
   */
  AddPrefix createAddPrefix();

  /**
   * Returns a new object of class '<em>Add Suffix</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Add Suffix</em>'.
   * @generated
   */
  AddSuffix createAddSuffix();

  /**
   * Returns a new object of class '<em>Filter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Filter</em>'.
   * @generated
   */
  Filter createFilter();

  /**
   * Returns a new object of class '<em>Threshold</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Threshold</em>'.
   * @generated
   */
  Threshold createThreshold();

  /**
   * Returns a new object of class '<em>Top N</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Top N</em>'.
   * @generated
   */
  TopN createTopN();

  /**
   * Returns a new object of class '<em>Bottom N</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Bottom N</em>'.
   * @generated
   */
  BottomN createBottomN();

  /**
   * Returns a new object of class '<em>Op Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Op Type</em>'.
   * @generated
   */
  OpType createOpType();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  DataRetrievalPackage getDataRetrievalPackage();

} //DataRetrievalFactory
