/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.dr.dataRetrieval;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.dr.dataRetrieval.DataRetrievalFactory
 * @model kind="package"
 * @generated
 */
public interface DataRetrievalPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "dataRetrieval";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/dr/DataRetrieval";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "dataRetrieval";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DataRetrievalPackage eINSTANCE = org.xtext.example.dr.dataRetrieval.impl.DataRetrievalPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.dr.dataRetrieval.impl.RetrieveImpl <em>Retrieve</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dr.dataRetrieval.impl.RetrieveImpl
   * @see org.xtext.example.dr.dataRetrieval.impl.DataRetrievalPackageImpl#getRetrieve()
   * @generated
   */
  int RETRIEVE = 0;

  /**
   * The feature id for the '<em><b>Dest</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RETRIEVE__DEST = 0;

  /**
   * The feature id for the '<em><b>Source Folder</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RETRIEVE__SOURCE_FOLDER = 1;

  /**
   * The feature id for the '<em><b>Config List</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RETRIEVE__CONFIG_LIST = 2;

  /**
   * The feature id for the '<em><b>Op List</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RETRIEVE__OP_LIST = 3;

  /**
   * The number of structural features of the '<em>Retrieve</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RETRIEVE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.dr.dataRetrieval.impl.DestImpl <em>Dest</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dr.dataRetrieval.impl.DestImpl
   * @see org.xtext.example.dr.dataRetrieval.impl.DataRetrievalPackageImpl#getDest()
   * @generated
   */
  int DEST = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEST__NAME = 0;

  /**
   * The number of structural features of the '<em>Dest</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEST_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.dr.dataRetrieval.impl.SourceFolderImpl <em>Source Folder</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dr.dataRetrieval.impl.SourceFolderImpl
   * @see org.xtext.example.dr.dataRetrieval.impl.DataRetrievalPackageImpl#getSourceFolder()
   * @generated
   */
  int SOURCE_FOLDER = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOURCE_FOLDER__NAME = 0;

  /**
   * The number of structural features of the '<em>Source Folder</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOURCE_FOLDER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.dr.dataRetrieval.impl.ConfigListImpl <em>Config List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dr.dataRetrieval.impl.ConfigListImpl
   * @see org.xtext.example.dr.dataRetrieval.impl.DataRetrievalPackageImpl#getConfigList()
   * @generated
   */
  int CONFIG_LIST = 3;

  /**
   * The feature id for the '<em><b>Source</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIG_LIST__SOURCE = 0;

  /**
   * The feature id for the '<em><b>Path</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIG_LIST__PATH = 1;

  /**
   * The feature id for the '<em><b>Keys To Extract</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIG_LIST__KEYS_TO_EXTRACT = 2;

  /**
   * The feature id for the '<em><b>Rename All</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIG_LIST__RENAME_ALL = 3;

  /**
   * The feature id for the '<em><b>Filter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIG_LIST__FILTER = 4;

  /**
   * The feature id for the '<em><b>Threshold</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIG_LIST__THRESHOLD = 5;

  /**
   * The number of structural features of the '<em>Config List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIG_LIST_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link org.xtext.example.dr.dataRetrieval.impl.OpListImpl <em>Op List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dr.dataRetrieval.impl.OpListImpl
   * @see org.xtext.example.dr.dataRetrieval.impl.DataRetrievalPackageImpl#getOpList()
   * @generated
   */
  int OP_LIST = 4;

  /**
   * The feature id for the '<em><b>Op Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OP_LIST__OP_TYPE = 0;

  /**
   * The number of structural features of the '<em>Op List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OP_LIST_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.dr.dataRetrieval.impl.SourceImpl <em>Source</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dr.dataRetrieval.impl.SourceImpl
   * @see org.xtext.example.dr.dataRetrieval.impl.DataRetrievalPackageImpl#getSource()
   * @generated
   */
  int SOURCE = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOURCE__NAME = 0;

  /**
   * The number of structural features of the '<em>Source</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOURCE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.dr.dataRetrieval.impl.PathImpl <em>Path</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dr.dataRetrieval.impl.PathImpl
   * @see org.xtext.example.dr.dataRetrieval.impl.DataRetrievalPackageImpl#getPath()
   * @generated
   */
  int PATH = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATH__NAME = 0;

  /**
   * The number of structural features of the '<em>Path</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATH_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.dr.dataRetrieval.impl.KeysToExtractImpl <em>Keys To Extract</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dr.dataRetrieval.impl.KeysToExtractImpl
   * @see org.xtext.example.dr.dataRetrieval.impl.DataRetrievalPackageImpl#getKeysToExtract()
   * @generated
   */
  int KEYS_TO_EXTRACT = 7;

  /**
   * The feature id for the '<em><b>Key1</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KEYS_TO_EXTRACT__KEY1 = 0;

  /**
   * The number of structural features of the '<em>Keys To Extract</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KEYS_TO_EXTRACT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.dr.dataRetrieval.impl.KeyImpl <em>Key</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dr.dataRetrieval.impl.KeyImpl
   * @see org.xtext.example.dr.dataRetrieval.impl.DataRetrievalPackageImpl#getKey()
   * @generated
   */
  int KEY = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KEY__NAME = 0;

  /**
   * The feature id for the '<em><b>Rename</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KEY__RENAME = 1;

  /**
   * The number of structural features of the '<em>Key</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KEY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.dr.dataRetrieval.impl.RenameImpl <em>Rename</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dr.dataRetrieval.impl.RenameImpl
   * @see org.xtext.example.dr.dataRetrieval.impl.DataRetrievalPackageImpl#getRename()
   * @generated
   */
  int RENAME = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RENAME__NAME = 0;

  /**
   * The number of structural features of the '<em>Rename</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RENAME_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.dr.dataRetrieval.impl.RenameAllImpl <em>Rename All</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dr.dataRetrieval.impl.RenameAllImpl
   * @see org.xtext.example.dr.dataRetrieval.impl.DataRetrievalPackageImpl#getRenameAll()
   * @generated
   */
  int RENAME_ALL = 10;

  /**
   * The number of structural features of the '<em>Rename All</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RENAME_ALL_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.dr.dataRetrieval.impl.FullRenameImpl <em>Full Rename</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dr.dataRetrieval.impl.FullRenameImpl
   * @see org.xtext.example.dr.dataRetrieval.impl.DataRetrievalPackageImpl#getFullRename()
   * @generated
   */
  int FULL_RENAME = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FULL_RENAME__NAME = RENAME__NAME;

  /**
   * The feature id for the '<em><b>N</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FULL_RENAME__N = RENAME_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Full Rename</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FULL_RENAME_FEATURE_COUNT = RENAME_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.dr.dataRetrieval.impl.AddPrefixImpl <em>Add Prefix</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dr.dataRetrieval.impl.AddPrefixImpl
   * @see org.xtext.example.dr.dataRetrieval.impl.DataRetrievalPackageImpl#getAddPrefix()
   * @generated
   */
  int ADD_PREFIX = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_PREFIX__NAME = RENAME__NAME;

  /**
   * The number of structural features of the '<em>Add Prefix</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_PREFIX_FEATURE_COUNT = RENAME_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.dr.dataRetrieval.impl.AddSuffixImpl <em>Add Suffix</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dr.dataRetrieval.impl.AddSuffixImpl
   * @see org.xtext.example.dr.dataRetrieval.impl.DataRetrievalPackageImpl#getAddSuffix()
   * @generated
   */
  int ADD_SUFFIX = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_SUFFIX__NAME = RENAME__NAME;

  /**
   * The number of structural features of the '<em>Add Suffix</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_SUFFIX_FEATURE_COUNT = RENAME_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.dr.dataRetrieval.impl.FilterImpl <em>Filter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dr.dataRetrieval.impl.FilterImpl
   * @see org.xtext.example.dr.dataRetrieval.impl.DataRetrievalPackageImpl#getFilter()
   * @generated
   */
  int FILTER = 14;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILTER__NAME = 0;

  /**
   * The number of structural features of the '<em>Filter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILTER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.dr.dataRetrieval.impl.ThresholdImpl <em>Threshold</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dr.dataRetrieval.impl.ThresholdImpl
   * @see org.xtext.example.dr.dataRetrieval.impl.DataRetrievalPackageImpl#getThreshold()
   * @generated
   */
  int THRESHOLD = 15;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int THRESHOLD__VALUE = 0;

  /**
   * The number of structural features of the '<em>Threshold</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int THRESHOLD_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.dr.dataRetrieval.impl.TopNImpl <em>Top N</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dr.dataRetrieval.impl.TopNImpl
   * @see org.xtext.example.dr.dataRetrieval.impl.DataRetrievalPackageImpl#getTopN()
   * @generated
   */
  int TOP_N = 16;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOP_N__VALUE = THRESHOLD__VALUE;

  /**
   * The number of structural features of the '<em>Top N</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOP_N_FEATURE_COUNT = THRESHOLD_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.dr.dataRetrieval.impl.BottomNImpl <em>Bottom N</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dr.dataRetrieval.impl.BottomNImpl
   * @see org.xtext.example.dr.dataRetrieval.impl.DataRetrievalPackageImpl#getBottomN()
   * @generated
   */
  int BOTTOM_N = 17;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOTTOM_N__VALUE = THRESHOLD__VALUE;

  /**
   * The number of structural features of the '<em>Bottom N</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOTTOM_N_FEATURE_COUNT = THRESHOLD_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.dr.dataRetrieval.impl.OpTypeImpl <em>Op Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dr.dataRetrieval.impl.OpTypeImpl
   * @see org.xtext.example.dr.dataRetrieval.impl.DataRetrievalPackageImpl#getOpType()
   * @generated
   */
  int OP_TYPE = 18;

  /**
   * The feature id for the '<em><b>Average</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OP_TYPE__AVERAGE = 0;

  /**
   * The feature id for the '<em><b>Sum</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OP_TYPE__SUM = 1;

  /**
   * The feature id for the '<em><b>All</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OP_TYPE__ALL = 2;

  /**
   * The feature id for the '<em><b>Key1</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OP_TYPE__KEY1 = 3;

  /**
   * The number of structural features of the '<em>Op Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OP_TYPE_FEATURE_COUNT = 4;


  /**
   * Returns the meta object for class '{@link org.xtext.example.dr.dataRetrieval.Retrieve <em>Retrieve</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Retrieve</em>'.
   * @see org.xtext.example.dr.dataRetrieval.Retrieve
   * @generated
   */
  EClass getRetrieve();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.dr.dataRetrieval.Retrieve#getDest <em>Dest</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Dest</em>'.
   * @see org.xtext.example.dr.dataRetrieval.Retrieve#getDest()
   * @see #getRetrieve()
   * @generated
   */
  EReference getRetrieve_Dest();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.dr.dataRetrieval.Retrieve#getSourceFolder <em>Source Folder</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Source Folder</em>'.
   * @see org.xtext.example.dr.dataRetrieval.Retrieve#getSourceFolder()
   * @see #getRetrieve()
   * @generated
   */
  EReference getRetrieve_SourceFolder();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.dr.dataRetrieval.Retrieve#getConfigList <em>Config List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Config List</em>'.
   * @see org.xtext.example.dr.dataRetrieval.Retrieve#getConfigList()
   * @see #getRetrieve()
   * @generated
   */
  EReference getRetrieve_ConfigList();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.dr.dataRetrieval.Retrieve#getOpList <em>Op List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Op List</em>'.
   * @see org.xtext.example.dr.dataRetrieval.Retrieve#getOpList()
   * @see #getRetrieve()
   * @generated
   */
  EReference getRetrieve_OpList();

  /**
   * Returns the meta object for class '{@link org.xtext.example.dr.dataRetrieval.Dest <em>Dest</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Dest</em>'.
   * @see org.xtext.example.dr.dataRetrieval.Dest
   * @generated
   */
  EClass getDest();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.dr.dataRetrieval.Dest#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.dr.dataRetrieval.Dest#getName()
   * @see #getDest()
   * @generated
   */
  EAttribute getDest_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.dr.dataRetrieval.SourceFolder <em>Source Folder</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Source Folder</em>'.
   * @see org.xtext.example.dr.dataRetrieval.SourceFolder
   * @generated
   */
  EClass getSourceFolder();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.dr.dataRetrieval.SourceFolder#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.dr.dataRetrieval.SourceFolder#getName()
   * @see #getSourceFolder()
   * @generated
   */
  EAttribute getSourceFolder_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.dr.dataRetrieval.ConfigList <em>Config List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Config List</em>'.
   * @see org.xtext.example.dr.dataRetrieval.ConfigList
   * @generated
   */
  EClass getConfigList();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.dr.dataRetrieval.ConfigList#getSource <em>Source</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Source</em>'.
   * @see org.xtext.example.dr.dataRetrieval.ConfigList#getSource()
   * @see #getConfigList()
   * @generated
   */
  EReference getConfigList_Source();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.dr.dataRetrieval.ConfigList#getPath <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Path</em>'.
   * @see org.xtext.example.dr.dataRetrieval.ConfigList#getPath()
   * @see #getConfigList()
   * @generated
   */
  EReference getConfigList_Path();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.dr.dataRetrieval.ConfigList#getKeysToExtract <em>Keys To Extract</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Keys To Extract</em>'.
   * @see org.xtext.example.dr.dataRetrieval.ConfigList#getKeysToExtract()
   * @see #getConfigList()
   * @generated
   */
  EReference getConfigList_KeysToExtract();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.dr.dataRetrieval.ConfigList#getRenameAll <em>Rename All</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rename All</em>'.
   * @see org.xtext.example.dr.dataRetrieval.ConfigList#getRenameAll()
   * @see #getConfigList()
   * @generated
   */
  EReference getConfigList_RenameAll();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.dr.dataRetrieval.ConfigList#getFilter <em>Filter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Filter</em>'.
   * @see org.xtext.example.dr.dataRetrieval.ConfigList#getFilter()
   * @see #getConfigList()
   * @generated
   */
  EReference getConfigList_Filter();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.dr.dataRetrieval.ConfigList#getThreshold <em>Threshold</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Threshold</em>'.
   * @see org.xtext.example.dr.dataRetrieval.ConfigList#getThreshold()
   * @see #getConfigList()
   * @generated
   */
  EReference getConfigList_Threshold();

  /**
   * Returns the meta object for class '{@link org.xtext.example.dr.dataRetrieval.OpList <em>Op List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Op List</em>'.
   * @see org.xtext.example.dr.dataRetrieval.OpList
   * @generated
   */
  EClass getOpList();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.dr.dataRetrieval.OpList#getOpType <em>Op Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Op Type</em>'.
   * @see org.xtext.example.dr.dataRetrieval.OpList#getOpType()
   * @see #getOpList()
   * @generated
   */
  EReference getOpList_OpType();

  /**
   * Returns the meta object for class '{@link org.xtext.example.dr.dataRetrieval.Source <em>Source</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Source</em>'.
   * @see org.xtext.example.dr.dataRetrieval.Source
   * @generated
   */
  EClass getSource();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.dr.dataRetrieval.Source#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.dr.dataRetrieval.Source#getName()
   * @see #getSource()
   * @generated
   */
  EAttribute getSource_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.dr.dataRetrieval.Path <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Path</em>'.
   * @see org.xtext.example.dr.dataRetrieval.Path
   * @generated
   */
  EClass getPath();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.dr.dataRetrieval.Path#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.dr.dataRetrieval.Path#getName()
   * @see #getPath()
   * @generated
   */
  EAttribute getPath_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.dr.dataRetrieval.KeysToExtract <em>Keys To Extract</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Keys To Extract</em>'.
   * @see org.xtext.example.dr.dataRetrieval.KeysToExtract
   * @generated
   */
  EClass getKeysToExtract();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.dr.dataRetrieval.KeysToExtract#getKey1 <em>Key1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Key1</em>'.
   * @see org.xtext.example.dr.dataRetrieval.KeysToExtract#getKey1()
   * @see #getKeysToExtract()
   * @generated
   */
  EReference getKeysToExtract_Key1();

  /**
   * Returns the meta object for class '{@link org.xtext.example.dr.dataRetrieval.Key <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Key</em>'.
   * @see org.xtext.example.dr.dataRetrieval.Key
   * @generated
   */
  EClass getKey();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.dr.dataRetrieval.Key#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.dr.dataRetrieval.Key#getName()
   * @see #getKey()
   * @generated
   */
  EAttribute getKey_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.dr.dataRetrieval.Key#getRename <em>Rename</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rename</em>'.
   * @see org.xtext.example.dr.dataRetrieval.Key#getRename()
   * @see #getKey()
   * @generated
   */
  EReference getKey_Rename();

  /**
   * Returns the meta object for class '{@link org.xtext.example.dr.dataRetrieval.Rename <em>Rename</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rename</em>'.
   * @see org.xtext.example.dr.dataRetrieval.Rename
   * @generated
   */
  EClass getRename();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.dr.dataRetrieval.Rename#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.dr.dataRetrieval.Rename#getName()
   * @see #getRename()
   * @generated
   */
  EAttribute getRename_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.dr.dataRetrieval.RenameAll <em>Rename All</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rename All</em>'.
   * @see org.xtext.example.dr.dataRetrieval.RenameAll
   * @generated
   */
  EClass getRenameAll();

  /**
   * Returns the meta object for class '{@link org.xtext.example.dr.dataRetrieval.FullRename <em>Full Rename</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Full Rename</em>'.
   * @see org.xtext.example.dr.dataRetrieval.FullRename
   * @generated
   */
  EClass getFullRename();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.dr.dataRetrieval.FullRename#getN <em>N</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>N</em>'.
   * @see org.xtext.example.dr.dataRetrieval.FullRename#getN()
   * @see #getFullRename()
   * @generated
   */
  EAttribute getFullRename_N();

  /**
   * Returns the meta object for class '{@link org.xtext.example.dr.dataRetrieval.AddPrefix <em>Add Prefix</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Add Prefix</em>'.
   * @see org.xtext.example.dr.dataRetrieval.AddPrefix
   * @generated
   */
  EClass getAddPrefix();

  /**
   * Returns the meta object for class '{@link org.xtext.example.dr.dataRetrieval.AddSuffix <em>Add Suffix</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Add Suffix</em>'.
   * @see org.xtext.example.dr.dataRetrieval.AddSuffix
   * @generated
   */
  EClass getAddSuffix();

  /**
   * Returns the meta object for class '{@link org.xtext.example.dr.dataRetrieval.Filter <em>Filter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Filter</em>'.
   * @see org.xtext.example.dr.dataRetrieval.Filter
   * @generated
   */
  EClass getFilter();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.dr.dataRetrieval.Filter#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.dr.dataRetrieval.Filter#getName()
   * @see #getFilter()
   * @generated
   */
  EAttribute getFilter_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.dr.dataRetrieval.Threshold <em>Threshold</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Threshold</em>'.
   * @see org.xtext.example.dr.dataRetrieval.Threshold
   * @generated
   */
  EClass getThreshold();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.dr.dataRetrieval.Threshold#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.dr.dataRetrieval.Threshold#getValue()
   * @see #getThreshold()
   * @generated
   */
  EAttribute getThreshold_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.dr.dataRetrieval.TopN <em>Top N</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Top N</em>'.
   * @see org.xtext.example.dr.dataRetrieval.TopN
   * @generated
   */
  EClass getTopN();

  /**
   * Returns the meta object for class '{@link org.xtext.example.dr.dataRetrieval.BottomN <em>Bottom N</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bottom N</em>'.
   * @see org.xtext.example.dr.dataRetrieval.BottomN
   * @generated
   */
  EClass getBottomN();

  /**
   * Returns the meta object for class '{@link org.xtext.example.dr.dataRetrieval.OpType <em>Op Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Op Type</em>'.
   * @see org.xtext.example.dr.dataRetrieval.OpType
   * @generated
   */
  EClass getOpType();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.dr.dataRetrieval.OpType#getAverage <em>Average</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Average</em>'.
   * @see org.xtext.example.dr.dataRetrieval.OpType#getAverage()
   * @see #getOpType()
   * @generated
   */
  EAttribute getOpType_Average();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.dr.dataRetrieval.OpType#getSum <em>Sum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Sum</em>'.
   * @see org.xtext.example.dr.dataRetrieval.OpType#getSum()
   * @see #getOpType()
   * @generated
   */
  EAttribute getOpType_Sum();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.dr.dataRetrieval.OpType#getAll <em>All</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>All</em>'.
   * @see org.xtext.example.dr.dataRetrieval.OpType#getAll()
   * @see #getOpType()
   * @generated
   */
  EAttribute getOpType_All();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.dr.dataRetrieval.OpType#getKey1 <em>Key1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Key1</em>'.
   * @see org.xtext.example.dr.dataRetrieval.OpType#getKey1()
   * @see #getOpType()
   * @generated
   */
  EReference getOpType_Key1();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  DataRetrievalFactory getDataRetrievalFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.dr.dataRetrieval.impl.RetrieveImpl <em>Retrieve</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dr.dataRetrieval.impl.RetrieveImpl
     * @see org.xtext.example.dr.dataRetrieval.impl.DataRetrievalPackageImpl#getRetrieve()
     * @generated
     */
    EClass RETRIEVE = eINSTANCE.getRetrieve();

    /**
     * The meta object literal for the '<em><b>Dest</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RETRIEVE__DEST = eINSTANCE.getRetrieve_Dest();

    /**
     * The meta object literal for the '<em><b>Source Folder</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RETRIEVE__SOURCE_FOLDER = eINSTANCE.getRetrieve_SourceFolder();

    /**
     * The meta object literal for the '<em><b>Config List</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RETRIEVE__CONFIG_LIST = eINSTANCE.getRetrieve_ConfigList();

    /**
     * The meta object literal for the '<em><b>Op List</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RETRIEVE__OP_LIST = eINSTANCE.getRetrieve_OpList();

    /**
     * The meta object literal for the '{@link org.xtext.example.dr.dataRetrieval.impl.DestImpl <em>Dest</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dr.dataRetrieval.impl.DestImpl
     * @see org.xtext.example.dr.dataRetrieval.impl.DataRetrievalPackageImpl#getDest()
     * @generated
     */
    EClass DEST = eINSTANCE.getDest();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEST__NAME = eINSTANCE.getDest_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.dr.dataRetrieval.impl.SourceFolderImpl <em>Source Folder</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dr.dataRetrieval.impl.SourceFolderImpl
     * @see org.xtext.example.dr.dataRetrieval.impl.DataRetrievalPackageImpl#getSourceFolder()
     * @generated
     */
    EClass SOURCE_FOLDER = eINSTANCE.getSourceFolder();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SOURCE_FOLDER__NAME = eINSTANCE.getSourceFolder_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.dr.dataRetrieval.impl.ConfigListImpl <em>Config List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dr.dataRetrieval.impl.ConfigListImpl
     * @see org.xtext.example.dr.dataRetrieval.impl.DataRetrievalPackageImpl#getConfigList()
     * @generated
     */
    EClass CONFIG_LIST = eINSTANCE.getConfigList();

    /**
     * The meta object literal for the '<em><b>Source</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONFIG_LIST__SOURCE = eINSTANCE.getConfigList_Source();

    /**
     * The meta object literal for the '<em><b>Path</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONFIG_LIST__PATH = eINSTANCE.getConfigList_Path();

    /**
     * The meta object literal for the '<em><b>Keys To Extract</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONFIG_LIST__KEYS_TO_EXTRACT = eINSTANCE.getConfigList_KeysToExtract();

    /**
     * The meta object literal for the '<em><b>Rename All</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONFIG_LIST__RENAME_ALL = eINSTANCE.getConfigList_RenameAll();

    /**
     * The meta object literal for the '<em><b>Filter</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONFIG_LIST__FILTER = eINSTANCE.getConfigList_Filter();

    /**
     * The meta object literal for the '<em><b>Threshold</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONFIG_LIST__THRESHOLD = eINSTANCE.getConfigList_Threshold();

    /**
     * The meta object literal for the '{@link org.xtext.example.dr.dataRetrieval.impl.OpListImpl <em>Op List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dr.dataRetrieval.impl.OpListImpl
     * @see org.xtext.example.dr.dataRetrieval.impl.DataRetrievalPackageImpl#getOpList()
     * @generated
     */
    EClass OP_LIST = eINSTANCE.getOpList();

    /**
     * The meta object literal for the '<em><b>Op Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OP_LIST__OP_TYPE = eINSTANCE.getOpList_OpType();

    /**
     * The meta object literal for the '{@link org.xtext.example.dr.dataRetrieval.impl.SourceImpl <em>Source</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dr.dataRetrieval.impl.SourceImpl
     * @see org.xtext.example.dr.dataRetrieval.impl.DataRetrievalPackageImpl#getSource()
     * @generated
     */
    EClass SOURCE = eINSTANCE.getSource();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SOURCE__NAME = eINSTANCE.getSource_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.dr.dataRetrieval.impl.PathImpl <em>Path</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dr.dataRetrieval.impl.PathImpl
     * @see org.xtext.example.dr.dataRetrieval.impl.DataRetrievalPackageImpl#getPath()
     * @generated
     */
    EClass PATH = eINSTANCE.getPath();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PATH__NAME = eINSTANCE.getPath_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.dr.dataRetrieval.impl.KeysToExtractImpl <em>Keys To Extract</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dr.dataRetrieval.impl.KeysToExtractImpl
     * @see org.xtext.example.dr.dataRetrieval.impl.DataRetrievalPackageImpl#getKeysToExtract()
     * @generated
     */
    EClass KEYS_TO_EXTRACT = eINSTANCE.getKeysToExtract();

    /**
     * The meta object literal for the '<em><b>Key1</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference KEYS_TO_EXTRACT__KEY1 = eINSTANCE.getKeysToExtract_Key1();

    /**
     * The meta object literal for the '{@link org.xtext.example.dr.dataRetrieval.impl.KeyImpl <em>Key</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dr.dataRetrieval.impl.KeyImpl
     * @see org.xtext.example.dr.dataRetrieval.impl.DataRetrievalPackageImpl#getKey()
     * @generated
     */
    EClass KEY = eINSTANCE.getKey();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute KEY__NAME = eINSTANCE.getKey_Name();

    /**
     * The meta object literal for the '<em><b>Rename</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference KEY__RENAME = eINSTANCE.getKey_Rename();

    /**
     * The meta object literal for the '{@link org.xtext.example.dr.dataRetrieval.impl.RenameImpl <em>Rename</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dr.dataRetrieval.impl.RenameImpl
     * @see org.xtext.example.dr.dataRetrieval.impl.DataRetrievalPackageImpl#getRename()
     * @generated
     */
    EClass RENAME = eINSTANCE.getRename();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RENAME__NAME = eINSTANCE.getRename_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.dr.dataRetrieval.impl.RenameAllImpl <em>Rename All</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dr.dataRetrieval.impl.RenameAllImpl
     * @see org.xtext.example.dr.dataRetrieval.impl.DataRetrievalPackageImpl#getRenameAll()
     * @generated
     */
    EClass RENAME_ALL = eINSTANCE.getRenameAll();

    /**
     * The meta object literal for the '{@link org.xtext.example.dr.dataRetrieval.impl.FullRenameImpl <em>Full Rename</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dr.dataRetrieval.impl.FullRenameImpl
     * @see org.xtext.example.dr.dataRetrieval.impl.DataRetrievalPackageImpl#getFullRename()
     * @generated
     */
    EClass FULL_RENAME = eINSTANCE.getFullRename();

    /**
     * The meta object literal for the '<em><b>N</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FULL_RENAME__N = eINSTANCE.getFullRename_N();

    /**
     * The meta object literal for the '{@link org.xtext.example.dr.dataRetrieval.impl.AddPrefixImpl <em>Add Prefix</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dr.dataRetrieval.impl.AddPrefixImpl
     * @see org.xtext.example.dr.dataRetrieval.impl.DataRetrievalPackageImpl#getAddPrefix()
     * @generated
     */
    EClass ADD_PREFIX = eINSTANCE.getAddPrefix();

    /**
     * The meta object literal for the '{@link org.xtext.example.dr.dataRetrieval.impl.AddSuffixImpl <em>Add Suffix</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dr.dataRetrieval.impl.AddSuffixImpl
     * @see org.xtext.example.dr.dataRetrieval.impl.DataRetrievalPackageImpl#getAddSuffix()
     * @generated
     */
    EClass ADD_SUFFIX = eINSTANCE.getAddSuffix();

    /**
     * The meta object literal for the '{@link org.xtext.example.dr.dataRetrieval.impl.FilterImpl <em>Filter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dr.dataRetrieval.impl.FilterImpl
     * @see org.xtext.example.dr.dataRetrieval.impl.DataRetrievalPackageImpl#getFilter()
     * @generated
     */
    EClass FILTER = eINSTANCE.getFilter();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FILTER__NAME = eINSTANCE.getFilter_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.dr.dataRetrieval.impl.ThresholdImpl <em>Threshold</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dr.dataRetrieval.impl.ThresholdImpl
     * @see org.xtext.example.dr.dataRetrieval.impl.DataRetrievalPackageImpl#getThreshold()
     * @generated
     */
    EClass THRESHOLD = eINSTANCE.getThreshold();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute THRESHOLD__VALUE = eINSTANCE.getThreshold_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.dr.dataRetrieval.impl.TopNImpl <em>Top N</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dr.dataRetrieval.impl.TopNImpl
     * @see org.xtext.example.dr.dataRetrieval.impl.DataRetrievalPackageImpl#getTopN()
     * @generated
     */
    EClass TOP_N = eINSTANCE.getTopN();

    /**
     * The meta object literal for the '{@link org.xtext.example.dr.dataRetrieval.impl.BottomNImpl <em>Bottom N</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dr.dataRetrieval.impl.BottomNImpl
     * @see org.xtext.example.dr.dataRetrieval.impl.DataRetrievalPackageImpl#getBottomN()
     * @generated
     */
    EClass BOTTOM_N = eINSTANCE.getBottomN();

    /**
     * The meta object literal for the '{@link org.xtext.example.dr.dataRetrieval.impl.OpTypeImpl <em>Op Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dr.dataRetrieval.impl.OpTypeImpl
     * @see org.xtext.example.dr.dataRetrieval.impl.DataRetrievalPackageImpl#getOpType()
     * @generated
     */
    EClass OP_TYPE = eINSTANCE.getOpType();

    /**
     * The meta object literal for the '<em><b>Average</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OP_TYPE__AVERAGE = eINSTANCE.getOpType_Average();

    /**
     * The meta object literal for the '<em><b>Sum</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OP_TYPE__SUM = eINSTANCE.getOpType_Sum();

    /**
     * The meta object literal for the '<em><b>All</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OP_TYPE__ALL = eINSTANCE.getOpType_All();

    /**
     * The meta object literal for the '<em><b>Key1</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OP_TYPE__KEY1 = eINSTANCE.getOpType_Key1();

  }

} //DataRetrievalPackage
