/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.dr.dataRetrieval;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Full Rename</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.dr.dataRetrieval.FullRename#getN <em>N</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.dr.dataRetrieval.DataRetrievalPackage#getFullRename()
 * @model
 * @generated
 */
public interface FullRename extends Rename
{
  /**
   * Returns the value of the '<em><b>N</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>N</em>' attribute.
   * @see #setN(String)
   * @see org.xtext.example.dr.dataRetrieval.DataRetrievalPackage#getFullRename_N()
   * @model
   * @generated
   */
  String getN();

  /**
   * Sets the value of the '{@link org.xtext.example.dr.dataRetrieval.FullRename#getN <em>N</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>N</em>' attribute.
   * @see #getN()
   * @generated
   */
  void setN(String value);

} // FullRename
