/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.dr.dataRetrieval;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Key</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.dr.dataRetrieval.Key#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.dr.dataRetrieval.Key#getRename <em>Rename</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.dr.dataRetrieval.DataRetrievalPackage#getKey()
 * @model
 * @generated
 */
public interface Key extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.dr.dataRetrieval.DataRetrievalPackage#getKey_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.dr.dataRetrieval.Key#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Rename</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rename</em>' containment reference.
   * @see #setRename(Rename)
   * @see org.xtext.example.dr.dataRetrieval.DataRetrievalPackage#getKey_Rename()
   * @model containment="true"
   * @generated
   */
  Rename getRename();

  /**
   * Sets the value of the '{@link org.xtext.example.dr.dataRetrieval.Key#getRename <em>Rename</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rename</em>' containment reference.
   * @see #getRename()
   * @generated
   */
  void setRename(Rename value);

} // Key
