/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.dr.dataRetrieval;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Op Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.dr.dataRetrieval.OpType#getAverage <em>Average</em>}</li>
 *   <li>{@link org.xtext.example.dr.dataRetrieval.OpType#getSum <em>Sum</em>}</li>
 *   <li>{@link org.xtext.example.dr.dataRetrieval.OpType#getAll <em>All</em>}</li>
 *   <li>{@link org.xtext.example.dr.dataRetrieval.OpType#getKey1 <em>Key1</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.dr.dataRetrieval.DataRetrievalPackage#getOpType()
 * @model
 * @generated
 */
public interface OpType extends EObject
{
  /**
   * Returns the value of the '<em><b>Average</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Average</em>' attribute.
   * @see #setAverage(String)
   * @see org.xtext.example.dr.dataRetrieval.DataRetrievalPackage#getOpType_Average()
   * @model
   * @generated
   */
  String getAverage();

  /**
   * Sets the value of the '{@link org.xtext.example.dr.dataRetrieval.OpType#getAverage <em>Average</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Average</em>' attribute.
   * @see #getAverage()
   * @generated
   */
  void setAverage(String value);

  /**
   * Returns the value of the '<em><b>Sum</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sum</em>' attribute.
   * @see #setSum(String)
   * @see org.xtext.example.dr.dataRetrieval.DataRetrievalPackage#getOpType_Sum()
   * @model
   * @generated
   */
  String getSum();

  /**
   * Sets the value of the '{@link org.xtext.example.dr.dataRetrieval.OpType#getSum <em>Sum</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sum</em>' attribute.
   * @see #getSum()
   * @generated
   */
  void setSum(String value);

  /**
   * Returns the value of the '<em><b>All</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>All</em>' attribute.
   * @see #setAll(String)
   * @see org.xtext.example.dr.dataRetrieval.DataRetrievalPackage#getOpType_All()
   * @model
   * @generated
   */
  String getAll();

  /**
   * Sets the value of the '{@link org.xtext.example.dr.dataRetrieval.OpType#getAll <em>All</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>All</em>' attribute.
   * @see #getAll()
   * @generated
   */
  void setAll(String value);

  /**
   * Returns the value of the '<em><b>Key1</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.dr.dataRetrieval.Key}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Key1</em>' containment reference list.
   * @see org.xtext.example.dr.dataRetrieval.DataRetrievalPackage#getOpType_Key1()
   * @model containment="true"
   * @generated
   */
  EList<Key> getKey1();

} // OpType
