/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.dr.dataRetrieval;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rename All</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.dr.dataRetrieval.DataRetrievalPackage#getRenameAll()
 * @model
 * @generated
 */
public interface RenameAll extends EObject
{
} // RenameAll
