/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.dr.dataRetrieval;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Retrieve</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.dr.dataRetrieval.Retrieve#getDest <em>Dest</em>}</li>
 *   <li>{@link org.xtext.example.dr.dataRetrieval.Retrieve#getSourceFolder <em>Source Folder</em>}</li>
 *   <li>{@link org.xtext.example.dr.dataRetrieval.Retrieve#getConfigList <em>Config List</em>}</li>
 *   <li>{@link org.xtext.example.dr.dataRetrieval.Retrieve#getOpList <em>Op List</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.dr.dataRetrieval.DataRetrievalPackage#getRetrieve()
 * @model
 * @generated
 */
public interface Retrieve extends EObject
{
  /**
   * Returns the value of the '<em><b>Dest</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dest</em>' containment reference.
   * @see #setDest(Dest)
   * @see org.xtext.example.dr.dataRetrieval.DataRetrievalPackage#getRetrieve_Dest()
   * @model containment="true"
   * @generated
   */
  Dest getDest();

  /**
   * Sets the value of the '{@link org.xtext.example.dr.dataRetrieval.Retrieve#getDest <em>Dest</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dest</em>' containment reference.
   * @see #getDest()
   * @generated
   */
  void setDest(Dest value);

  /**
   * Returns the value of the '<em><b>Source Folder</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source Folder</em>' containment reference.
   * @see #setSourceFolder(SourceFolder)
   * @see org.xtext.example.dr.dataRetrieval.DataRetrievalPackage#getRetrieve_SourceFolder()
   * @model containment="true"
   * @generated
   */
  SourceFolder getSourceFolder();

  /**
   * Sets the value of the '{@link org.xtext.example.dr.dataRetrieval.Retrieve#getSourceFolder <em>Source Folder</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source Folder</em>' containment reference.
   * @see #getSourceFolder()
   * @generated
   */
  void setSourceFolder(SourceFolder value);

  /**
   * Returns the value of the '<em><b>Config List</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.dr.dataRetrieval.ConfigList}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Config List</em>' containment reference list.
   * @see org.xtext.example.dr.dataRetrieval.DataRetrievalPackage#getRetrieve_ConfigList()
   * @model containment="true"
   * @generated
   */
  EList<ConfigList> getConfigList();

  /**
   * Returns the value of the '<em><b>Op List</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.dr.dataRetrieval.OpList}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op List</em>' containment reference list.
   * @see org.xtext.example.dr.dataRetrieval.DataRetrievalPackage#getRetrieve_OpList()
   * @model containment="true"
   * @generated
   */
  EList<OpList> getOpList();

} // Retrieve
