/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.dr.dataRetrieval;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Top N</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.dr.dataRetrieval.DataRetrievalPackage#getTopN()
 * @model
 * @generated
 */
public interface TopN extends Threshold
{
} // TopN
