/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example.dr.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class DataRetrievalUiModule extends AbstractDataRetrievalUiModule {

	public DataRetrievalUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
