/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.dr.dataRetrieval.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.dr.dataRetrieval.AddSuffix;
import org.xtext.example.dr.dataRetrieval.DataRetrievalPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Add Suffix</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class AddSuffixImpl extends RenameImpl implements AddSuffix
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AddSuffixImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DataRetrievalPackage.Literals.ADD_SUFFIX;
  }

} //AddSuffixImpl
