/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.dr.dataRetrieval.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.dr.dataRetrieval.BottomN;
import org.xtext.example.dr.dataRetrieval.DataRetrievalPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Bottom N</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class BottomNImpl extends ThresholdImpl implements BottomN
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BottomNImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DataRetrievalPackage.Literals.BOTTOM_N;
  }

} //BottomNImpl
