/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.dr.dataRetrieval.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.dr.dataRetrieval.DataRetrievalPackage;
import org.xtext.example.dr.dataRetrieval.TopN;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Top N</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class TopNImpl extends ThresholdImpl implements TopN
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TopNImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DataRetrievalPackage.Literals.TOP_N;
  }

} //TopNImpl
