/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example.dr.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDataRetrievalScopeProvider extends DelegatingScopeProvider {
}
