/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example.dr.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.dr.DataRetrievalRuntimeModule;
import org.xtext.example.dr.DataRetrievalStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class DataRetrievalIdeSetup extends DataRetrievalStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new DataRetrievalRuntimeModule(), new DataRetrievalIdeModule()));
	}
	
}
