/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example.dr;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class DataRetrievalStandaloneSetup extends DataRetrievalStandaloneSetupGenerated {

	public static void doSetup() {
		new DataRetrievalStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
